### ISSUE TITLE
GitService.getRepository method can be confusing

### ISSUE THREAD

**Issue by ia3andy** [fabric8-launcher/launcher-backend#101]
We could improve the comment in GitService to explain what the method is returning depending on repository fullName or just name as input in method getRepository.

Or it may be clearer to have:

- getRepository(String repositoryFullName) //checked syntax for repositoryFullName (<owner>/<name>)
- getOwnedRepository(String repositoryName) // repositoryName must not contain "/"
- getRepository(GitOrganization organization, String repositoryName) // repositoryName must not contain "/"

**Comment by gastaldi** [comment]
Now sure if we should have a getOwnedRepository method. In the majority of user cases you don't know if the repository name belongs to you or some other organization. That's what getRepository should handle afaik

**Comment by ia3andy** [comment]
Gitlab implementation is as you say, but our github implementation is doing something else for example, this is the reason why I proposed :
` 
if (repositoryName.contains("/")) {
                String[] split = repositoryName.split("/");
                return getRepository(ImmutableGitOrganization.of(split[0]), split[1]);
            } else {
                return getRepository(ImmutableGitOrganization.of(delegate.getMyself().getLogin()), repositoryName);
            }
`
A change in the doc to explain it is afaik may already be enough though.
