### ISSUE TITLE
BitbucketServiceFactoryImpl support for TokenIdentity

### ISSUE THREAD

**Issue by ia3andy** [fabric8-launcher/launcher-backend#105]
It needs to be tested with a oauth token as well.

**Comment by gastaldi** [comment]
Remove support for UserPasswordIdentity too. Even in a non-keycloak environment as with the GitHub provider, we only specify the username and the token

**Comment by ia3andy** [comment]
@gastaldi we need to discuss this (just after the readme discussion maybe :p ). As talked with @quintesse, I think it's still needed.

**Comment by quintesse** [comment]
@ia3andy I think you need to write down _why_ you think we still need this. This has two advantages: a) people can read later what was this about and b) perhaps @gastaldi will just agree with your reasoning and you don't need to have any BJ calls. :)

**Comment by ia3andy** [comment]
As discused:

I think it still makes sense to use it. At the end it's really close to a token (from github) since you generate it from the interface exactly like a token, the only difference is that you put it in the header as basic auth (base64 with userid). I don't know why they didn't call it a token and used Bearer Authentication.

We can't use only token authentication because tokens given by oauth are short expired tokens and therefore not usable for tests.
