### ISSUE TITLE
Improve KeyCloak info in README.md

### ISSUE THREAD

**Issue by ia3andy** [fabric8-launcher/launcher-backend#106]
Make clearer that there is 2 executions modes:

- with official or local KC (link to configuration)
- without KC -> needs credentials for services if not in simulation mode

**Comment by quintesse** [comment]
> if not in simulation mode

I'd say that's not part of the "base" explanation, but only when explaining how to do testing. (In which case you could simply say: for testing you need to use setup "A) Running without KC")

**Comment by ia3andy** [comment]
Maybe I don't understand something but I still ask to make that clear for me.. :p

```
final String authorization = request.getHeader(HttpHeaders.AUTHORIZATION);
        GitServiceFactory gitServiceFactory = getGitServiceFactory(request);
        Identity identity;
        String token = request.getHeader(GIT_TOKEN_HEADER);
        if (token != null) {
            identity = IdentityFactory.createFromToken(token);
        } else {
            identity = gitServiceFactory.getDefaultIdentity()
                    .orElseGet(
                            () -> identityProvider.getIdentity(gitServiceFactory.getName().toLowerCase(), authorization)
                                    .orElseThrow(() -> new NotFoundException("Git token not found"))
                    );
        }
        return gitServiceFactory.create(identity);
```

This code and the fact that Github default credentials are required are the reason I am confuse. 

Would the getDefaultIdentity() which retrieve the environment credentials be used in production?

**Comment by gastaldi** [comment]
In production the orElseGet part would be used, because getDefaultIdentity() would be empty

**Comment by ia3andy** [comment]
```
@Override
    public Optional<Identity> getDefaultIdentity() {
        // Try using the provided Github token
        return Optional.ofNullable(getToken())
                .map(IdentityFactory::createFromToken);
    }

    private String getToken() {
        return EnvironmentSupport.INSTANCE.getRequiredEnvVarOrSysProp(LAUNCHER_MISSIONCONTROL_GITHUB_TOKEN);
    }
```
It would throw an exception then..

**Comment by gastaldi** [comment]
@ia3andy yes, that would throw an exception and looks wrong IMHO
