### ISSUE TITLE
Remove GitUser.getEmail

### ISSUE THREAD

**Issue by gastaldi** [fabric8-launcher/launcher-backend#109]
Retrieving the emails involves in some Git providers a new request, and this information is not being used anywhere. We should consider removing it

**Comment by gastaldi** [comment]
@ia3andy want to work in this?

**Comment by ia3andy** [comment]
@quintesse @gastaldi I saw you debating about this on Slack, should we still remove it?

**Comment by quintesse** [comment]
Yeah, we can remove it
