### ISSUE TITLE
Add OSIO tokens to the list of environment variables for integration tests and in the README

### ISSUE THREAD

**Issue by gastaldi** [fabric8-launcher/launcher-backend#118]
Integration tests for for OSIO require an [authentication token](https://fabric8-services.github.io/fabric8-auth/reference.html#_automated_tests). I placed in an environment variable named **LAUNCHER_OSIO_TOKEN**. 
It would be nice to have this token in our [launcher-env-template.sh](https://github.com/fabric8-launcher/launcher-backend/blob/master/launcher-env-template.sh) with a link to the instructions on how to generate.

Be aware that the staging token is different compared to the production token. They are fetched from different OSIO authentication servers (auth.prod-preview.openshift.io and auth.openshift.io - staging and production respectively). So to test the backend I have **LAUNCHER_OSIO_PROD_TOKEN** and **LAUNCHER_OSIO_STAGING_TOKEN**, so I can invoke the services like: 

```bash
$ http --form GET http://localhost:8080/api/services/git/user "Authorization:Bearer $LAUNCHER_OSIO_STAGING_TOKEN" X-App:osio --timeout 100

HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 106
Content-Type: application/json
Date: Tue, 27 Feb 2018 22:23:02 GMT

{
    "avatarUrl": "https://avatars1.githubusercontent.com/u/30807733?v=4",
    "login": "gastaldi-osio"
}

```

**Comment by gastaldi** [comment]
This is from @alexey from the OSIO Auth team: 

>You can use Oauth2 flow if you prefer JSON responses - https://fabric8-services.github.io/fabric8-auth/reference.html#_oauth2_0_login

>And I hope you are not generating offline tokens for manual testing/development? They are supposed to be used in automated tests only. Please use your user token for development and manual testing. You can get your user token from the user profile page.

**Comment by ia3andy** [comment]
@gastaldi 
> Integration tests for for OSIO require an authentication token. I placed in an environment variable named OSIO_TOKEN.

I don't really understand what you want here, it seems that the environment variable doesn't exist yet and therefore is not used by any IT. 

Do you mean it is going to be used by future IT (that will be created in #186)?

**Comment by gastaldi** [comment]
That is exactly what I meant. This environment variable is only set in the CI server and there are no integration tests using it at the moment

**Comment by gastaldi** [comment]
@ia3andy the correct variable name set in CI is `LAUNCHER_OSIO_TOKEN`, I edited the issue description to fix this
