### ISSUE TITLE
Make sure the protected endpoints require an Authorization token

### ISSUE THREAD

**Issue by gastaldi** [fabric8-launcher/launcher-backend#122]
Otherwise, return a 401 immediately.

**Comment by invincibleJai** [comment]
@gastaldi it works fine for git and launch APIs but for runtimes , missions , pipelines it works even without Auth token as in 

`curl -X GET "https://forge.api.prod-preview.openshift.io/api/booster-catalog/runtimes" -H "accept: application/json" -H "X-App: osio"`

Are those need not be protected?

**Comment by gastaldi** [comment]
@invincibleJai there isn't any information in there that requires the user to be logged in, unless I am missing something :smile:

**Comment by invincibleJai** [comment]
Thanks , got it just wanted to be sure :)
