### ISSUE TITLE
Add a checkstyle validation on PR

### ISSUE THREAD

**Issue by ia3andy** [fabric8-launcher/launcher-backend#133]
I don't know if it should be part of CI or another tool..

@gastaldi  said:
we can reuse what's used in the wildfly-swarm repositories

https://github.com/wildfly-swarm/checkstyle

The checkstyle config that is used by all projects in the WildFly Swarm organisation
or create our own which may be better I think

**Comment by ia3andy** [comment]
should we do it as part of the pom.xml using maven checkstyle plugin?
https://maven.apache.org/plugins/maven-checkstyle-plugin/usage.html

**Comment by gastaldi** [comment]
Yes, that is a good idea

**Comment by ia3andy** [comment]
@gastaldi you are lightning fast

**Comment by gastaldi** [comment]
We can assume that checkstyle should always run during `mvn install`, unless explicitly disabled with the `-Dcheckstyle.skip` flag

**Comment by ia3andy** [comment]
I am using wildfly swarm checktyle:

`
[ERROR] src/main/java/io/fabric8/launcher/base/identity/UserPasswordIdentity.java:[36] (blocks) NeedBraces: L'instruction 'if' devrait utiliser des accolades ('{' et '}').
`
Should I change equals? or remove this rule (it's a generated equals).

```Java
     @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        UserPasswordIdentity that = (UserPasswordIdentity) o;

        if (!username.equals(that.username)) return false;
        return password != null ? password.equals(that.password) : that.password == null;
    }
```

**Comment by ia3andy** [comment]
hmmmm, I will follow the rule we have in the:
`ide-configs/idea/fabric8-launcher.xml`

And this rule is disabled there..
