### ISSUE TITLE
Remove LAUNCHER_TESTS_TRUSTSTORE_PATH from script

### ISSUE THREAD

**Issue by gastaldi** [fabric8-launcher/launcher-backend#137]
Now that the Hoverfly keystore is part of the launcher-base-test JAR, check if it's possible to point to the keystore file inside that JAR (or copy to a temp dir) instead of having to explicitly specify it in the tests

**Comment by ia3andy** [comment]
@gastaldi it is now possible to point in the jar. Good idea to try to copy it to a temp dir, I am going to try that :)

**Comment by quintesse** [comment]
"Now" or "not"?

**Comment by ia3andy** [comment]
oupsy.. I changed to not ;)

**Comment by quintesse** [comment]
Ah hehe, I thought so, I was already wondering why you'd want to ways of doing this

**Comment by ia3andy** [comment]
Copy to temp directory is working, I clean the code and I submit a new PR :)

**Comment by quintesse** [comment]
Try to make it "auto delete on exit" if you can :)

**Comment by gastaldi** [comment]
Or perhaps use a fixed filename in the /tmp dir to avoid creating this file for each test

**Comment by quintesse** [comment]
Eww @gastaldi , what's that for kind of solution you're proposing? Don't listen to that coal miner pretending to be a programmer Andy 😛

**Comment by gastaldi** [comment]
My point was just to avoid having a separate JKS file for each test but maybe that doesn't make sense, so ignore me in this one :smile:

**Comment by gastaldi** [comment]
Although the `coal miner pretending to be a programmer` was a bit uncalled for, but that's ok

**Comment by quintesse** [comment]
I apologize if the joke wasn't well received, sorry,
