### ISSUE TITLE
Give a way to filter out repositories given a string parameter

### ISSUE THREAD

**Issue by ia3andy** [fabric8-launcher/launcher-backend#174]
It would look like this:
```
// In repositories belonging to the logged user
searchRepositories(GitRepositoryFilter filter)

// In repositories belonging to the specified organization
searchRepositories(GitOrganization organization, GitRepositoryFilter filter)

GitRepositoryFilter {
    +withNameContaining
}
```

**Comment by quintesse** [comment]
If you really want to use a separate `GitRepositoryFilter` interface please make sure it's a SAM interface so we can easily use it with lambdas:

    searchRepositories(r -> r.getName().contains("foo"))

But in general I'd just use `Predicate`s directly, just like we do in the Booster Catalog Service. So the above would become:

    // In repositories belonging to the logged user
    searchRepositories(Predicate<GitRepository> filter)

and if you really want the overload with the organization (because you think it will be used a lot) you could implement it something like this (pseudocode):

    // In repositories belonging to the specified organization
    searchRepositories(GitOrganization organization, Predicate<GitRepository> filter) {
        return repos.stream().filter(withOrganization(organization).and(filter));
    }

    public static PredicateGitRepository> withOrganization(GitOrganization organization) {
        return (GitRepository r) -> r.getOrganization().equals(organization);
    }

Wdyt?

**Comment by gastaldi** [comment]
I think having predicates or other kind of filter besides the repository name may not work because I was expecting this filtering to happen in the API server for performance reasons.

**Comment by quintesse** [comment]
Ok, seeing the `GitRepositoryFilter` I assumed we were talking about free filtering.

Also if the API supports that, sure, but I don't think the GitHub API does that, right? But perhaps some of the others do, I don't know.

**Comment by gastaldi** [comment]
@quintesse yes, I think you're right. Judging by https://developer.github.com/v3/repos/#list-user-repositories there isn't much that can be done about it.

**Comment by ia3andy** [comment]
```Java
/**
     * Search repositories.
     */
    public GHRepositorySearchBuilder searchRepositories() {
        return new GHRepositorySearchBuilder(this);
    }

```

**Comment by gastaldi** [comment]
@ia3andy why not using the Predicates as @quintesse mentioned? I think that would be much easier, no?

**Comment by ia3andy** [comment]
Sorry I was not precise enough, the method is I copied is part of Kohsuke API. 
So for perf reason, I would prefer using the api instead of retrieving all the repositories and filtering after.

**Comment by gastaldi** [comment]
Ah yes, that makes sense :+1:
