### ISSUE TITLE
InvalidPathException: Malformed input or input contains unmappable characters: /tmp/importdir2062067929047671833/kubern...

### ISSUE THREAD

**Issue by gastaldi** [fabric8-launcher/launcher-backend#179]
https://errortracking.prod-preview.openshift.io/openshift_io/fabric8-launcher-backend/issues/1063/

```
InvalidPathException: Malformed input or input contains unmappable characters: /tmp/importdir2062067929047671833/kubernetes-basico-nginx/._aplicação.yaml5361234586827526215.tmp
    at sun.nio.fs.UnixPath.encode(UnixPath.java:147)
    at sun.nio.fs.UnixPath.<init>(UnixPath.java:71)
    at sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:281)
    at java.io.File.toPath(File.java:2234)
    at org.eclipse.jgit.util.FileUtils.isFile(FileUtils.java:761)
...
(69 additional frame(s) were not displayed)

Malformed input or input contains unmappable characters: /tmp/importdir2062067929047671833/kubernetes-basico-nginx/._aplicação.yaml5361234586827526215.tmp
```

**Comment by gastaldi** [comment]
This may help: https://stackoverflow.com/questions/22413421/git-error-malformed-input-or-input-contains-unmappable-chacraters

**Comment by gastaldi** [comment]
Repository where this error happened: https://github.com/concrete-cristian-trucco/kubernetes-basico-nginx

**Comment by ia3andy** [comment]
I've tried to reproduce locally with this code which passes:
```Java
        File tmpdir = Files.createTempDirectory("importdir").toFile();
        CloneCommand command = Git.cloneRepository();
        String gitUri = "https://github.com/concrete-cristian-trucco/kubernetes-basico-nginx.git";
        File basedir = new File(tmpdir, "kubernetes-basico-nginx");

        command = command.
                setCloneAllBranches(true).
                setURI(gitUri).
                setDirectory(basedir).setRemote("origin");

        command.call();
```

I think the bug is either related to the JRE used on prod-preview, the containing os, or the encoding JAVA_OPTS.

> This may help: https://stackoverflow.com/questions/22413421/git-error-malformed-input-or-input-contains-unmappable-chacraters

It seems this issue is related to eclipse. 

I found this link which say that setting LANG `export LANG=en_US.UTF-8` on the system may fix the problem:
https://github.com/src-d/engine/issues/244#issuecomment-349265922



Maybe this one can help too:
https://stackoverflow.com/questions/39185613/java-nio-file-invalidpathexception-malformed-input-or-input-contains-unmappable

**Comment by gastaldi** [comment]
@ia3andy I failed to reproduce that error locally too. Can you give it a try by running from the assembled Docker image?

You need to run:
`CICO_LOCAL=true cico_build_deploy.sh`

**Comment by gastaldi** [comment]
@ia3andy I think this is missing in Dockerfile.deploy: https://github.com/fabric8-launcher/launcher-backend/blob/master/Dockerfile.build#L7
