### ISSUE TITLE
Make build faster

### ISSUE THREAD

**Issue by ia3andy** [fabric8-launcher/launcher-backend#185]
`mvn clean install` in launcher addon starts a script named add-template-files.sh which is really slow because of a repository pull (nearly half the total build time in my case). 
-> look if there is a way to do the same thing quicker (or avoid doing it)

Look if there are other things slowing down the build.

**Comment by gastaldi** [comment]
Can this be closed? I still see the add-template-files.sh in core-impl though

**Comment by ia3andy** [comment]
We can close this.

> I still see the add-template-files.sh in core-impl though

Oupsy, it seems I forgot to delete it..
