### ISSUE TITLE
Space label applied to build configs should use ID instead of name

### ISSUE THREAD

**Issue by ebaron** [fabric8-launcher/launcher-backend#221]
Currently, we mark which space a build config belongs to with a label "space=_spacename_". A space's name is not guaranteed to be unique, and thus could cause name collisions with other users' spaces, or previously deleted and recreated spaces. A safer alternative would be to use the space ID (UUID), which is guaranteed to be unique.

Another thing we could consider is prefixing the label name to better distinguish it from the user's labels. e.g. "fabric8.io/space=_spaceID_".

**Comment by gastaldi** [comment]
@ebaron So changing https://github.com/fabric8-launcher/launcher-backend/blob/master/addons/osio-addon/src/main/java/io/fabric8/launcher/osio/steps/OpenShiftSteps.java#L60 to use the space UUID instead won't break the current behavior? Would you mind providing a PR with the changes?

**Comment by ebaron** [comment]
@gastaldi @aslakknutsen mentioned that the pipelines UI will need changes, as would the deployments backend. The latter is straightforward to fix, I'm not too familiar with the former. There could be other things that would break as well. We will have to identify what currently depends on the space label. I will try to find time to create a PR for this.

**Comment by gastaldi** [comment]
Seems to be resolved. Closing
