### ISSUE TITLE
Use SSE instead of Websockets

### ISSUE THREAD

**Issue by gastaldi** [fabric8-launcher/launcher-backend#244]
Parent: https://github.com/fabric8-launcher/launcher-planning/issues/148

**Comment by ia3andy** [comment]
This seems interesting, I will take it if nobody mind :)

Though depending on which load balancer we use, websocket sticky connection is possible.

**Comment by ia3andy** [comment]
Switching here for your comment in @gastaldi PR:

> I must agree that SSE is all we need as we don't need bi directional communication. But websockets are better supported in browsers and it's easier to detect if the browser is still connected. What would be the benefits of changing to SSE?

@edewit https://github.com/Yaffle/EventSource

**Comment by quintesse** [comment]
Some interesting information:

About the implementation of SSEs:
https://www.html5rocks.com/en/tutorials/eventsource/basics/

Some differences between SSEs and WebSockets:
https://streamdata.io/blog/push-sse-vs-websockets/

The first link shows that SSEs are basically long-polling, but built into the browser.
The last link briefly mentions that SSEs, being plain HTTP, work better with load-balancers and firewalls.

**Comment by gastaldi** [comment]
@ia3andy I assigned myself to the issue because I have already started working on it, but I'll let you review before I push my work when this is done

**Comment by gastaldi** [comment]
EventSource does not work with POST requests. Working on making sticky sessions in Openshift (see parent issue)
