### ISSUE TITLE
Make documentation readme fetching part of the runtime

### ISSUE THREAD

**Issue by ia3andy** [fabric8-launcher/launcher-backend#252]
It is currently done during the build using the `
addons/launcher-addon/add-template-files.sh` script.

The process should be close to the one used in the BCS. 

As part of issue #185, it will improve `mvn clean install` perf

**Comment by quintesse** [comment]
Take a look here: https://github.com/fabric8-launcher/launcher-booster-catalog-service/blob/master/src/main/java/io/fabric8/launcher/booster/catalog/AbstractBoosterCatalogService.java#L127-L208

It's the three places where we use `CompletableFuture`.

**Comment by quintesse** [comment]
We could have a `setupDocumentation()` or `initDocumentation()` or whatever that pre-fetches the contents (without doing an actual `get()` to block) while the code that actually needs the information could do a `,get()`. We could also have a `resetDocumentation()` or something similar to the `reindex()` method we have in the BCS. And we could call that from https://github.com/fabric8-launcher/launcher-backend/blob/master/web/src/main/java/io/fabric8/launcher/web/endpoints/BoosterCatalogEndpoint.java#L162 perhaps so that a reindex of the booster catalog also triggers a re-clone of the documentation.

**Comment by quintesse** [comment]
Btw, for doing the clone itself you can look here: https://github.com/fabric8-launcher/launcher-booster-catalog-service/blob/master/src/main/java/io/fabric8/launcher/booster/catalog/spi/NativeGitBoosterCatalogPathProvider.java#L55-L71

**Comment by gastaldi** [comment]
I wonder if the BCS has some sort of hook that we could attach to its lifecycle. Considering that everytime the booster is re-indexed the README should also be read again, I think that would be an interesting feature to have

**Comment by quintesse** [comment]
@gastaldi I don't think it makes much sense. The BCS doesn't have anything to do with reading the docs. And the one that triggers the re-indexing is the backend, so that one can simply also call the re-reading of the docs.

**Comment by ia3andy** [comment]
@quintesse regarding the clone part, IMO, using jgit may be a better idea (even in the BCS by the way).

**Comment by quintesse** [comment]
@ia3andy no, we used JGit before and we removed it. JGit can be extremely slow. Native Git is just better for this.

**Comment by ia3andy** [comment]
@quintesse this is a good reason ;)

**Comment by gastaldi** [comment]
JGit doesn't support partial fetches. That's why we're using native Git

**Comment by ia3andy** [comment]
@gastaldi that's another good reason hehe

**Comment by gastaldi** [comment]
>I wonder if the BCS has some sort of hook that we could attach to its lifecycle. Considering that everytime the booster is re-indexed the README should also be read again, I think that would be an interesting feature to have

I take that back, it's better to have the documentation in a separate endpoint, to be triggered as a webhook when changes to launcher-documentation are pushed

**Comment by quintesse** [comment]
Sure, I don't have a problem with that. The webhook thing makes sense. Remember though that if we at some point merge the READMEs into the Booster Catalog we'd either have to trigger 2 endpoints with a single change or we'd have to merge them after all.
