### ISSUE TITLE
Bring Git organizations ordered alphabetically from GitService.getOrganizations

### ISSUE THREAD

**Issue by gastaldi** [fabric8-launcher/launcher-backend#268]
![screenshot from 2018-04-05 11-40-28](https://user-images.githubusercontent.com/54133/38372974-7b6f389e-38c6-11e8-9f0d-b9ac404b670b.png)

**Comment by ia3andy** [comment]
why not just sorting them client side?

**Comment by gastaldi** [comment]
Why not sorting them server side? :)
