### ISSUE TITLE
Auto add 'not ready' status on PR's

### ISSUE THREAD

**Issue by ia3andy** [fabric8-launcher/launcher-backend#281]

**Comment by quintesse** [comment]
What's this exactly?

**Comment by ia3andy** [comment]
Sorry I didn't add the description in the first place, I added the issue as a reminder so that I don't forget :p

I am talking for everyone, but don't hesitate to correct me if I am wrong..

Very often, when you create or edit the PR, it is not yet ready for reviewing or for merging (you notice something is wrong, the IT fail, it is not up to date, ...).

The goal of this status would be to have an action saying: "ok guys you can start reviewing, my PR is ready"

**Comment by ia3andy** [comment]
`not ready` may be clearer

**Comment by ia3andy** [comment]
Decided not to use it automatically cause it may be confusing to contributors.

Created label https://github.com/fabric8-launcher/launcher-backend/labels/not%20ready%20yet to use manually.

**Comment by gastaldi** [comment]
Another idea is to name your PR with a `[WIP]` or `work-in-progress` prefix
