### ISSUE TITLE
Wildfly Swarm vs something else trial 

### ISSUE THREAD

**Issue by ia3andy** [fabric8-launcher/launcher-backend#284]
Discuss another technology to serve ou backend.
Make a run for it and compare with current.

**Comment by ia3andy** [comment]
What alternative framework than Wildfly Swarm other Red Hat teams are using?

**Comment by gastaldi** [comment]
The best candidate is to migrate to https://docs.thorntail.io/4.0.0-SNAPSHOT/ once it's released. It's a major rewrite of WildFly Swarm (faster tests execution - yay)

**Comment by ia3andy** [comment]
@gastaldi that sounds promising :)

**Comment by quintesse** [comment]
Interesting :)
