### ISSUE TITLE
Try to add a filter on CI to make it required only when the source code has changed

### ISSUE THREAD

**Issue by ia3andy** [fabric8-launcher/launcher-backend#306]
alien-ike/test-keeper seems to be already doing that.

**Comment by gastaldi** [comment]
This may be helpful: https://semaphoreci.com/blog/2012/11/15/skip-those-builds.html

**Comment by ia3andy** [comment]
added a comment on the blog post:
https://semaphoreci.com/blog/2012/11/15/skip-those-builds.html

**Comment by ia3andy** [comment]
I got an anwser from the SemaphoreCI team:

> Hi Andy,
> 
> Thank you for your message.
> 
> Unfortunately, Semaphore doesn't support skipping or canceling a build with a PR comment at the moment.
> However, I've noticed that we had similar request recently, and we'll consider its implementation in the future. I've added your vote towards supporting this.
> 
> If there’s anything else you would like to share with us, feel free to reach out.
> 
> Best,

**Comment by gastaldi** [comment]
Closing as there isn't much we can do about it
