### ISSUE TITLE
 /services/openshift/clusters/all should return an attribute for each cluster name saying if the token exists for the user

### ISSUE THREAD

**Issue by gastaldi** [fabric8-launcher/launcher-backend#313]

**Comment by edewit** [comment]
we only  need that if we would like to keep this page:
![screenshot from 2017-10-20 16-24-23](https://user-images.githubusercontent.com/51133/38742154-1261fe3c-3f3c-11e8-8326-a2f5a7b46b3d.png)

**Comment by ia3andy** [comment]
Returning an attribute for each cluster name saying if the token exists for the user means having a method mixing `/clusters` and `clusters/all`. We could change the method `/clusters` to do it and remove `clusters/all` which would become useless

Note: If this is needed, we could keep `clusters/all` for perf purpose if we just want to list all clusters without a call to keycloak for each of them..

**Comment by gastaldi** [comment]
>Note: If this is needed, we could keep clusters/all for perf purpose if we just want to list all clusters without a call to keycloak for each of them..

@ia3andy yes, that's the exact reason why `clusters/all` exists

**Comment by ia3andy** [comment]
@gastaldi I agree with you that `/clusters` should return a boolean for each cluster name saying if the token exists for the user. It gives more information with the same perf cost and can avoid a call to `clusters/all` in some situation.

**Comment by quintesse** [comment]
So if I understand this correctly, both with now return the same list, except for the fact that `clusters` will have an extra boolean indicating if a token exists (therefore being more expensive) while `clusters/all` just returns the list without the boolean (therefore being cheaper).

**Comment by gastaldi** [comment]
We can also return the cluster type in this same response, so the UI can handle each cluster differently (a different icon, etc)

**Comment by gastaldi** [comment]
Related: https://github.com/fabric8-launcher/launcher-backend/issues/327

**Comment by quintesse** [comment]
> We can also return the cluster type in this same response

Why not simple return the cluster document itself, with all the info that may or may not be in it?

**Comment by gastaldi** [comment]
Sure, that works too
