### ISSUE TITLE
 Create .ike-prow/test-keeper.yaml to exclude files from alien-ike check

### ISSUE THREAD

**Issue by gastaldi** [fabric8-launcher/launcher-backend#315]
As @bartoszmajsak mentioned in https://github.com/fabric8-launcher/launcher-backend/pull/314#issuecomment-381167285, we should exclude files that do not warrant a test check

**Comment by ia3andy** [comment]
Need to wait for PR in test-keeper to put test-keeper.yaml in .ike-prow/ directory.

@bartoszmajsak could you reference the PR here please?

**Comment by gastaldi** [comment]
Requires https://github.com/arquillian/ike-prow-plugins/issues/119

**Comment by bartoszmajsak** [comment]
Considering all of it is upstream and bot on prod supports that - which files do you want to exclude besides what's in the linked comment?

**Comment by gastaldi** [comment]
The files provided by upstream are fine. Closing it
