### ISSUE TITLE
Change LAUNCHER_TESTS_SV_SIMULATION variable for hoverfly simulation

### ISSUE THREAD

**Issue by ia3andy** [fabric8-launcher/launcher-backend#319]
The current `LAUNCHER_TESTS_SV_SIMULATION` naming does not make real sense.

I was thinking of inverting it and naming it `LAUNCHER_HOVERFLY_CAPTURE`. It could be better because the default value would be `false` and it's easier to remember.

**Comment by bartoszmajsak** [comment]
`SV` stands for `SERVICE VIRTUALIZATION`, maybe that's why. As I'm the responsible here just wanted to shed some light. I would personally avoid using `hoverfly` as it's "implementation detail" :)

**Comment by ia3andy** [comment]
>  I would personally avoid using hoverfly as it's "implementation detail"

We only use this environment variable when testing locally to capture the yaml.
So when we use it, we know it's for Hoverfly.

**Comment by ia3andy** [comment]
> SV stands for SERVICE VIRTUALIZATION, maybe that's why. As I'm the responsible here just wanted to shed some light.

Thanks for the clarification I wouldn't have guess hehe :)

**Comment by quintesse** [comment]
@ia3andy don't forget to update the `launcher-env-template.sh` file

**Comment by ia3andy** [comment]
@quintesse yes no worries.. there is not need to update it:
- Since we decided that hoverfly test are unit tests (no more integration) we only use this env var when recording new tests.
- Default value is recording `false` and it's not part of the `launcher-env-template.sh`

**Comment by quintesse** [comment]
AH ok! Wasn't it part of the script at some point? Or am I just imagining things?
