### ISSUE TITLE
remove LOCAL KeyCloak mode from the default start process 

### ISSUE THREAD

**Issue by ia3andy** [fabric8-launcher/launcher-backend#333]
Until we can provide a solution to make KC work with minishift: https://github.com/fabric8-launcher/launcher-planning/issues/156. KC is only working for GitHub which doesn't add a big value for developers.

I propose to remove LOCAL KeyCloak mode from our env scripts and README.md. The no/official KEYCLOAK modes are plenty enough.

Since there may are a few cases where it might still be needed, we should keep the documentation  and the setup somewhere.

**Comment by ia3andy** [comment]
@quintesse do you agree with this?

**Comment by quintesse** [comment]
Dunno. This _is_ for people working on the code after all, so if it's useful to _us_, even in a very limited way, why not keep the script? I do agree that it could be removed from the README, but I don't see anything in there mentioning the local keycloak mode?

**Comment by ia3andy** [comment]
Ok @quintesse I get you point.

This means I have to change the env script because it's falsy because openshift is not available in KC:
```
    # Local KeyCloak
    export LAUNCHER_KEYCLOAK_URL=http://localhost:8280/auth
    export LAUNCHER_KEYCLOAK_REALM=launch
    export LAUNCHER_MISSIONCONTROL_OPENSHIFT_CLUSTERS_FILE=$SCRIPT_DIR/clusters.yaml
```

We need to add a comment saying that for now local KC is only working with github and that this need to be specified (it wouldn't work as it is):
```
export LAUNCHER_MISSIONCONTROL_OPENSHIFT_USERNAME=developer
export LAUNCHER_MISSIONCONTROL_OPENSHIFT_PASSWORD=developer
# If set, will override username/password authentication scheme
    #export LAUNCHER_MISSIONCONTROL_OPENSHIFT_TOKEN=<token here>
```

@gastaldi Another thing, in the script, Minishift is only available in No KeyCloak mode. Why not putting it in local keycloak mode too?

**Comment by gastaldi** [comment]
@ia3andy sure, I guess that makes sense. I have to be honest that I have never used the `local` mode myself.
