### ISSUE TITLE
Separate CDI logic

### ISSUE THREAD

**Issue by ia3andy** [fabric8-launcher/launcher-backend#345]
Find a nice way to separate CDI logic from the actual classes (Using Producers may be a solution).
 
It would:
- Make our services CDI free just simple classes (without proxy or injection concerns)
- Keep the CDI logic in one place
- Simpler way to change CDI logic/framework if ever needed

**Comment by gastaldi** [comment]
I don't think I agree we should make our services CDI free, on the contrary, they should embrace the CDI annotations and `@Inject` as many dependencies as needed.

**Comment by gastaldi** [comment]
Now if you're talking about a specific module (`base/` for example) then I agree that it shouldn't use CDI annotations, but that is a special case and doesn't apply to other modules

**Comment by quintesse** [comment]
I do agree somewhat with @ia3andy here. Personally I'd use CDI only for injection in the "first level" of code. I'm not a great fan of all that "automagical wiring", I'd rather be explicit of who passes what to whom.

**Comment by gastaldi** [comment]
> Personally I'd use CDI only for injection in the "first level" of code.

What is a "first level" of code? Can you give an example?

> I'm not a great fan of all that "automagical wiring", I'd rather be explicit of who passes what to whom

You prefer ServiceLookups and Factories around the code instead of having an injected object? That looks like anti-patterns to me

**Comment by quintesse** [comment]
> What is a "first level" of code? Can you give an example?

Web endpoints for example. Where requests come in. The stuff that initiates computation.

> You prefer ServiceLookups and Factories around the code instead of having an injected object?

No, I prefer having things explicit. I don't like it at all that I see an `@Inject Foo` and then have to go looking around the code for some place where that `Foo` might come from. The moment you start adding selectors it gets even worse.

> That looks like anti-patterns to me

What? So code that doesn't use CDI is now an anti-pattern? All those decades that CDI didn't even exist we've been writing bad code? ;)

**Comment by quintesse** [comment]
Btw, I don't mind CDI at all. What I don't like is a) the proliferation of CDI annotations because to me that's doing exactly what CDI was meant to prevent: putting decisions about what and how to wire things together inside the code. IMO code that gets used in CDI should look exactly the same as if done when not using CDI. And b) the automagical part of it. But I actually quite like Guice's way of being able to wire things together in code.

I also understand that this isn't going away any time soon so I accept that people want to do this. And I also won't be campaigning to get rid of it in our code. But you also won't see me writing much of that kind of code.

**Comment by ia3andy** [comment]
@gastaldi @quintesse 

IMO:

At the end using producers is really close to using @inject on constructors:
- it just separates the injection logic from the class itself
- it lets you put this injection logic somewhere else (only in module web for example).
- It gives you a way to have different injection logic depending on the module you are using it

I don't think that separating injection logic from the classes means not embracing CDI concepts.

**Comment by ia3andy** [comment]
> I don't think that separating injection logic from the classes means not embracing CDI concepts.

@quintesse it's what I meant there too like Guice exactly..

**Comment by gastaldi** [comment]
Dependencies of a Service Classe are using constructors instead of private attributes. Closing this
