### ISSUE TITLE
Update system GH account used for first repo push

### ISSUE THREAD

**Issue by ALRubinger** [fabric8-launcher/launcher-backend#35]
![screenshot1](https://user-images.githubusercontent.com/199891/35492695-67fd0eea-047c-11e8-8d88-1f4d6a4047dd.png)

Should be: `developers.redhat.com/launch` or "Red Hat Developers Launch Service"

**Comment by quintesse** [comment]
This has to be an actual GH user, so there's not so much  leeway with the name. Perhaps it could be turned into `fabric8-launcher` or something like that? (The user itself could have a description that says "Red Hat Developers Launch Service" and points to the actual website)

**Comment by gastaldi** [comment]
@quintesse is right, however `fabric8-launcher` is a Github org and it is already taken :( 
We need to rename that user to something more adequate. Any thoughts @ALRubinger ?

**Comment by gastaldi** [comment]
@ALRubinger I want to use https://github.com/redhat-developers-launcher, but that user needs a valid certified e-mail to be able to be listed in commits

**Comment by gastaldi** [comment]
Fixed in https://github.com/fabric8-launcher/launcher-backend/commit/724381fecad32711ebad4ed70b9bb740b85eb2d7
