### ISSUE TITLE
Implement jwt token validation in SecuredFilter and handle No KC mode

### ISSUE THREAD

**Issue by ia3andy** [fabric8-launcher/launcher-backend#359]
SecuredFilter:61
```Java
    private void validateToken(String token) {
        // TODO: Check if the token was issued by the server and if it's not expired
        JWT.decode(token);
    }
```

**Comment by ia3andy** [comment]
We should handle No KC mode in this issue as well.
When No KeyCloak mode is activated, we should skip validation.

**Comment by ia3andy** [comment]
Hold until summit

**Comment by gastaldi** [comment]
Implemented in https://github.com/fabric8-launcher/launcher-backend/commit/cf45365fd13d97f3f9a31ec15e6c06a822f0d980
