### ISSUE TITLE
Give the possibility to "retry from" after an error 

### ISSUE THREAD

**Issue by ia3andy** [fabric8-launcher/launcher-backend#405]
Example:
- you forgot to delete the openshift app before (on a free cluster) 
- you start the launch process and it will fail after creating the github repository
- [New possibility] From there, you have the possibility to delete the app yourself, then go back to the wizard and click on "retry"

You just saved yourself the deletion of the git repository and a new wizard process.

**Comment by quintesse** [comment]
Well we _do_ already support retries in the backend AFAIK. We had them in the old Launcher after all. So I'm not sure if this is a backend issue or a frontend one.

**Comment by ia3andy** [comment]
@quintesse should I move this to planning then?

**Comment by quintesse** [comment]
That's probably a good idea yes. In general I'd use planning for cross-project issues and things that might need discussion or design and leave the project issue trackers for very technical stuff and implementation details.

**Comment by ia3andy** [comment]
moved to https://github.com/fabric8-launcher/launcher-planning/issues/164

**Comment by quintesse** [comment]
Was moved. Closing.
