### ISSUE TITLE
blocked by broken Login In & Authorize Account

### ISSUE THREAD

**Issue by vorburger** [fabric8-launcher/launcher-backend#496]
### Description

I'm following https://github.com/minishift/minishift-addons/tree/master/add-ons/fabric8-launcher :

```
minishift stop
minishift profile set launcher-addon
minishift config set memory 8192
git clone git@github.com:minishift/minishift-addons.git
minishift addon install minishift-addons/add-ons/fabric8-launcher/
minishift start
minishift addon apply fabric8-launcher --addon-env GITHUB_USERNAME=vorburger --addon-env GITHUB_TOKEN=...

```
### What should happen?

It should work. :smile: 

### What happens instead?

In the "Authorize Git Provider" section on the frontend the Username says None, when it probably shold show mine I passed in as `-addon-env GITHUB_USERNAME=` ? 

There is a blue "Login In & Authorize Account" button. Clicking in throws me back to the launcher homepage, instead of taking me to that usual "Launch is requesting additional permissions" page on GithHub.

### Do you have any idea why?

I guess this which appears on the browser console is bad news?

```
GET http://launcher-rhoarpad.192.168.42.251.nip.io/launch/api/services/git/user 401 (Unauthorized) @ zone.js:2969
User has not authorized GitHub: Backend returned code 401, body was: null @ app-launcher-gitprovider.service.ts:69
```

**Comment by vorburger** [comment]
I think my Personal Access Token is fine (have used it before). If I just forgot some.. scope, then it would be cool to get a clearer error mesage - but I suspect the problem is more fundamental than that. My https://github.com/settings/tokens also shows "Never used" for that token, so it probably never even hit GitHub.

**Comment by gastaldi** [comment]
@vorburger Have you also specified the Openshift API and Console URL and emptied the Keycloak parameters?

**Comment by vorburger** [comment]
>  specified the Openshift API and Console URL and emptied the Keycloak parameters?

@gastaldi yeah in [that minishift add-on that's done automatically, see here](https://github.com/minishift/minishift-addons/blob/master/add-ons/fabric8-launcher/fabric8-launcher.addon).

@edewit (and @ia3andy) thanks for the fix - it works (again) for me now.
