### ISSUE TITLE
Generate .vscode recommandations file

### ISSUE THREAD

**Issue by jeffmaury** [fabric8-launcher/launcher-backend#537]
### Description
As the adapters group is progressing, it should be good that the zip returned would contain .vscode recommandations files so that user will be suggested to install VSCode extensions relevant to the project (ex Java LSP, OpenShift tooling,...).
@mohitsuman would be able to provide the content of those files. Depending on the target date, the vscode fabric8 launcher extension could generate those files if the folder is not present in the zip (see fabric8-launcher/launcher-vscode-extension#10
...

### What should happen?
.vscode folder added to the zip with the relevant file(s)

...

### What happens instead?
No .vscode folder yet
...

### Do you have any idea why?

...

### Error log

```
If you have an error log, please paste it here.
```

**Comment by gastaldi** [comment]
@jeffmaury that's a good idea. It should be implemented as a `ProjectilePreparer` as in this [example](https://github.com/fabric8-launcher/launcher-backend/blob/master/core/core-impl/src/main/java/io/fabric8/launcher/core/impl/preparers/ChangeArquillianConfigurationPreparer.java)
