### ISSUE TITLE
Add a new git summary endpoint to reduce/group calls to backend

### ISSUE THREAD

**Issue by ia3andy** [fabric8-launcher/launcher-backend#546]
### Description

Currently the frontend load always generates 3 calls to retrieve all necessary git info:
- `/user`
- `/repositories`
- `/organizations`

The idea is to add a new endpoint grouping those three calls.. `/userSummary`.

@gastaldi @edewit @quintesse any counter argument?

**Comment by gastaldi** [comment]
-1, you don't need repositories belonging to different organizations in a single call

**Comment by quintesse** [comment]
Grouping `/users` and `/organizations` seems an easy win, there will probably be very few people that have enough organizations to start need pagination. But I wonder how you're thing to treat `/repositories`? Just only add the ones for the user itself and call `/repositories` separately when the user switches in the UI to a different organization? All of them? (Then we definitely would need pagination from the start)

**Comment by edewit** [comment]
Right now these once are for sure done in one call atm
1. it calls `/user`
   https://github.com/fabric8-launcher/launcher-frontend/blob/master/src/app/wizard/services/app-launcher-gitprovider.service.ts#L50
1. then `/organizations` when the result of `/user` is done
   https://github.com/fabric8-launcher/launcher-frontend/blob/master/src/app/wizard/services/app-launcher-gitprovider.service.ts#L53
1. Then we fetch all the users repositories to validate if the name one gives is not already taken (is it just me or is that a bit stupid) and on "OSIO import" we use it to make it easy for the user to pick an existing repo.

There is no pagination and we fetch all of this once the user is logged in. Once the user changes the organisation we query all the repositories for that organisation.
