### ISSUE TITLE
Create GitService.getRepositories

### ISSUE THREAD

**Issue by gastaldi** [fabric8-launcher/launcher-backend#55]
It should accept a GitOrganization as a parameter, like the following: 
```java
    /**
     * @param organization the organization that this set of repositories belong to.
     *                     Can be null, which in this case it will use the default organization the user is on
     * @return the repositories belonging to the given organization
     */
    List<GitRepository> getRepositories(GitOrganization organization);
```

This is for #48

**Comment by bartoszmajsak** [comment]
Let's use [lately introduced Service Virtualization](https://github.com/fabric8-launcher/launcher-backend/pull/37) while implementing this feature. Ping me if more details needed.

**Comment by quintesse** [comment]
In what way @bartoszmajsak ? I thought Hoverfly was mostly meant for testing purposes?

**Comment by bartoszmajsak** [comment]
In a way of using it for tests?

**Comment by quintesse** [comment]
Ah of course, it just seemed somehow that you were suggesting to actually use it for the _implementation_ itself. Sorry, was just misunderstanding things.

**Comment by bartoszmajsak** [comment]
Now, that would be interesting ;)

**Comment by quintesse** [comment]
I'm taking this if you don't mind @gastaldi ?

**Comment by quintesse** [comment]
Although I see you got it marked "good first issue"...

**Comment by gastaldi** [comment]
@quintesse sure. Ping me in Slack if you have any questions
