### ISSUE TITLE
Key not found for kid: 0lL0vXs9YRVqZMowyw8uNLR_yr0iFaozdQk9rzq2OVU

### ISSUE THREAD

**Issue by gastaldi** [fabric8-launcher/launcher-backend#563]
https://errortracking.prod-preview.openshift.io/openshift_io/fabric8-launcher-backend/issues/8970/

```
Key not found for kid: 0lL0vXs9YRVqZMowyw8uNLR_yr0iFaozdQk9rzq2OVU
```

**Comment by bartoszmajsak** [comment]
Root cause https://github.com/openshiftio/openshift.io/issues/4453

**Comment by gastaldi** [comment]
Fixed in production
