### ISSUE TITLE
Return Route/Service hostnames from Launch

### ISSUE THREAD

**Issue by quintesse** [fabric8-launcher/launcher-backend#605]
The frontend needs to know the URLs of the routes (for the services) that have been created.

Given the fact that creating resources is a dynamic process it might be a good option to have the websocket send this information once it is available.

**Comment by gastaldi** [comment]
@edewit @quintesse I modified the backend to send the routes during the `OPENSHIFT_PIPELINE` status message. It should return a `routes` parameter where the key is the route name and the value the exposed URL:

Here is an example returned from the WS when you deploy a Node.js Health Check booster: 

```json
{  
   "id":"9b05e4af-73d7-48a1-986a-0ac15e39fdbc",
   "data":{  
      "routes":{  
         "nodejs-health-check":"http://nodejs-health-check-fooabc.devtools-dev.ext.devshift.net"
      }
   },
   "statusMessage":"OPENSHIFT_PIPELINE"
}
```
