### ISSUE TITLE
Include Camel Tooling VS Code extension in recommended extension for Fuse boosters

### ISSUE THREAD

**Issue by apupier** [fabric8-launcher/launcher-backend#632]
### Description

 https://marketplace.visualstudio.com/items?itemName=camel-tooling.vscode-apache-camel

### What should happen?

Camel tooling will be suggested to be installed if not when using a Camel/Fuse booster

**Comment by gastaldi** [comment]
Fixed in https://github.com/fabric8-launcher/launcher-backend/commit/2f6b5a54b9315c48560e9c06c3eba4dc3aa5849c
