### ISSUE TITLE
Use Extension Pack for Camel instead of listing all extensions

### ISSUE THREAD

**Issue by apupier** [fabric8-launcher/launcher-backend#649]
### Description

it will avoid to have a long list of recommended extensions, installation will be easier.

### What should happen?

...

### What happens instead?

...

### Do you have any idea why?

...

### Error log

```
If you have an error log, please paste it here.
```

**Comment by gastaldi** [comment]
@jeffmaury I think you may be interested in this issue?

**Comment by gastaldi** [comment]
@apupier can you elaborate more on the issue? Are you talking about https://github.com/fabric8-launcher/launcher-backend/blob/master/core/core-impl/src/main/resources/vscode/fuse/extensions.json? 

Mind providing a fix?
