### ISSUE TITLE
Improve CheStackDetector

### ISSUE THREAD

**Issue by gastaldi** [fabric8-launcher/launcher-backend#66]
From @quintesse in https://github.com/fabric8-launcher/launcher-backend/commit/dc44d87bfee9bde4fbd738bc52ad059cfc8d73b7#commitcomment-27376869:

> 
> I think this should be rewritten to use specialized subclasses, right? I mean you could have an interface like:
> 
> ```
> interface StackDetector {
>     CheStack detect(Path projectLocation);
> ```
> 
> and then have several implementations, like for example a specific `MavenDependencyStackDetector` which just looks at the dependencies. It would take a dependency name as argument and you'd create 3 of them: one for each of the POM-based stacks. And have another implementation, eg: `NodeJsStackDetector` that just check for the existence of a `package.json`.
> 
> That seems better than just hard-coding it all into a single class, don't you think?

**Comment by gastaldi** [comment]
AFAIK this file contains all the stacks supported by Che: 

https://github.com/redhat-developer/rh-che/blob/master/assembly/fabric8-stacks/src/main/resources/stacks.json

**Comment by quintesse** [comment]
Not sure if that's really useful, I mean we'd still have to hard-code any detection code, so once you do that you can just as well hard-code the list itself too.
Now, if on the other hand they have code to do detection themselves then we should definitely use that!

**Comment by quintesse** [comment]
I talked with someone on the Che team and it seems somewhat unlikely that they would make detection code. A) because they don't have anything like that yet and B) because the stack mechanism is going to change, so any future detection code will likely be based on that new system. So better we keep this way of doing things for now.

**Comment by quintesse** [comment]
Why close it? It still think we could make it a bit better than it is now, right? 😄

**Comment by gastaldi** [comment]
Not worth spending the effort in this if it's going to change
