### ISSUE TITLE
Additional information on /booster-catalog/booster API

### ISSUE THREAD

**Issue by gorkem** [fabric8-launcher/launcher-backend#68]
Che requires additional information on a booster in order to generate workspaces. We can use the `/booster-catalog/booster` to retrieve some of this information however we need the information captured on `.openshiftio/application.yml` and [configmap.properties](https://github.com/fabric8-launcher/launcher-documentation/blob/master/docs/topics/readme/cd-configmap-vert.x.properties) to be provided via the API.

**Comment by gastaldi** [comment]
@gorkem can you summarize what you need specifically from these files in this issue? This may probably be a hint for us to improve the boosters' metadata in the booster-catalog

**Comment by gastaldi** [comment]
This issue was moved to fabric8-launcher/launcher-planning#107
