### ISSUE TITLE
Use hoverfly in MissionControlIT

### ISSUE THREAD

**Issue by ia3andy** [fabric8-launcher/launcher-backend#98]
After that:
- we will be able to use fake credentials for git (github, gitlab, bitbucket) in env (README.md)
- we can remove the need to create accounts in README.md to run integration tests

**Comment by quintesse** [comment]
> we can remove the need to create accounts in README.md to run integration tests

That would definitely be nice ;)

**Comment by gastaldi** [comment]
That would be nice. In my https://github.com/fabric8-launcher/launcher-backend/pull/75 I miss the integration credentials for the services and that could be overridden by using hoverfly. But I guess at some point we'd like to test the whole flow without any mocked services

**Comment by gastaldi** [comment]
I already have an openshift account and a GitHub test account. Just need to talk to the SD team to add the credentials as Jenkins secrets and then the tests should pass

**Comment by ia3andy** [comment]
At the mean time, ask them to add a test account for bitbucket then:
`
export LAUNCHER_MISSIONCONTROL_BITBUCKET_USERNAME=<username>
export LAUNCHER_MISSIONCONTROL_BITBUCKET_APPLICATION_PASSWORD=<app_pass>
`

**Comment by ia3andy** [comment]
I think we should wait for the decision in the ML.
https://groups.google.com/forum/#!topic/fabric8-launcher/z5oPtiXORLY

 Plus, I think we should have a look to see it is possible to use hoverfly for this at all.

**Comment by ia3andy** [comment]
I am closing this one since we decided that we will not use hoverfly on IT.

We still use hoverfly to mock external service endpoint in unit tests (ex GitHubServiceTest).
